changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Best Crush
      labels:
        - best-crush
    - title: DofusDB CLI
      labels:
        - dofusdb-cli
    - title: DofusDB API Clients
      labels:
        - dofusdb-api
    - title: Dofocus API Clients
      labels:
        - dofocus-api
    - title: Other Changes
      labels:
        - "*"