changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Best Crush
      labels:
        - best-crush
    - title: DofusDB API Clients and CLI
      labels:
        - dofusdb
    - title: Dofocus API Clients
      labels:
        - dofocus-api
    - title: Other Changes
      labels:
        - "*"