# configuration file for dotnet-releaser
[msbuild]
project = "DofusDbCommunity.sln"
[github]
user = "ismailbennani"
repo = "DofusDBCommunity"
version_prefix = "v"
[brew]
publish = false
[service]
publish = false