name: Continuous Deployment - Publish Best Crush

on:
  release:
    types: published
  workflow_dispatch:
    dry-run:
      description: Skip the publication of packages to repos
      required: true
      type: boolean
      default: false

jobs:
  compute-version:
    name: Compute version
    uses: ./.github/workflows/reusable-compute-version.yml
    with:
      build-name: pr

  build-publish:
    name: Build Best Crush
    
    runs-on: windows-latest
    needs: compute-version
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET 10.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install MAUI
        run: dotnet workload install maui

      - name: Build
        run: dotnet build DofusSharp.BestCrush.Filter.slnf --configuration Release --property Version=${{ needs.compute-version.outputs.version }}

      - name: Test
        run: dotnet test DofusSharp.BestCrush.Filter.slnf --configuration Release --no-build

      - name: Publish
        run: dotnet publish BestCrush/BestCrush.csproj --output nsis/BestCrush/app/ --configuration Release --framework net10.0-windows10.0.19041.0 --self-contained true --property WindowsAppSDKSelfContained --no-build --property Version=${{ needs.compute-version.outputs.version }} --property DebugSymbols=false --property DebugType=None

      - name: Upload compiled application to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: best-crush-${{ needs.compute-version.outputs.version-short }}-windows
          path: nsis/BestCrush/app/
          if-no-files-found: 'error'

  create-installer:
    name: Create installer
    
    runs-on: windows-latest
    needs:
      - compute-version
      - build-publish
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download compiled application from artifacts
        uses: actions/download-artifact@v4
        with:
          name: best-crush-${{ needs.compute-version.outputs.version-short }}-windows
          path: nsis/BestCrush/app/

      - name: Install NSIS
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          buckets: extras
          apps: nsis

      - name: Download Windows App SDK
        run: |
          mkdir nsis/BestCrush/redist
          iwr "https://aka.ms/windowsappsdk/1.6/1.6.250602001/windowsappruntimeinstall-x64.exe" -OutFile "nsis/BestCrush/app/redist/WindowsAppRuntimeInstall-x64.exe"

      - name: Create installer
        run: |
          cd nsis/BestCrush
          (Get-Content best-crush.nsi) -replace '__VERSION__', '${{ needs.compute-version.outputs.version-short }}' | Out-File -encoding UTF8 best-crush.nsi
          makensis best-crush.nsi

      - name: Upload installer to release
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: nsis/BestCrush/*.exe
          tag: ${{ github.ref }}

      - name: Upload installer to artifacts
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          path: nsis/BestCrush/*.exe
          if-no-files-found: 'error'