name: Continuous Deployment - Publish DofusDB CLI

on:
  release:
    types: published
  workflow_dispatch:
    inputs:
      dry-run:
        description: Skip the publication to repos
        required: true
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  compute-version:
    name: Compute version
    uses: ./.github/workflows/reusable-compute-version.yml
    with:
      build-name: release

  build-test:
    name: Build and test DofusDB CLI
    runs-on: ubuntu-latest
    needs: compute-version

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install .NET 10.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Build
        run: dotnet build DofusSharp.DofusDb.Cli.Filter.slnf --configuration Release --property Version=${{ needs.compute-version.outputs.version }}

      - name: Test
        run: dotnet test DofusSharp.DofusDb.Cli.Filter.slnf --configuration Release --no-build

  build-publish-nuget:
    name: Build DofusDB CLI
    runs-on: ubuntu-latest
    needs: [compute-version, build-test]
    
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install .NET 10.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Pack
        run: dotnet pack DofusSharp.DofusDb.Cli/DofusSharp.DofusDb.Cli.csproj --output nuget/ --configuration Release --property Version=${{ needs.compute-version.outputs.version }}

      - name: Configure Github Nuget repository
        if: ${{ !inputs.dry-run }}
        run: dotnet nuget add source --username ismailbennani --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DofusSharp/index.json"

      - name: Publish nugets - Github
        if: ${{ !inputs.dry-run }}
        run: |
          for filename in nuget/*.nupkg; do
              dotnet nuget push "$filename" --source github --api-key ${{ secrets.GITHUB_TOKEN }}
          done

      - name: Publish nugets - Nuget
        if: ${{ !inputs.dry-run }}
        run: |
          for filename in nuget/*.nupkg; do
              dotnet nuget push "$filename" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
          done

      - name: Upload tool as artifact
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: libraries
          path: nuget/*.nupkg
          if-no-files-found: error

  build-publish-binaries:
    name: Build DofusDB CLI
    needs: [compute-version, build-test]
    strategy:
      matrix:
        - runner: ubuntu-latest
          rid: linux-x64
        - runner: windows-latest
          rid: win-x64
        - runner: macos-latest 
          rid: osx-x64
        
    runs-on: ${{ matrix.runner }}

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install .NET 10.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Publish
        run: dotnet publish DofusSharp.DofusDb.Cli/DofusSharp.DofusDb.Cli.csproj --output nuget/ --configuration Release --property RuntimeIdentifier=${{ matrix.rid }} --property Version=${{ needs.compute-version.outputs.version }}

      - name: Archive binaries
        run: 7z a -tzip dist/dofusdb-${{ matrix.rid }}.zip dist/dofusdb.exe

      - name: Upload binaries to release
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/dofusdb-${{ matrix.rid }}.zip
          asset_name: dofusdb-${{ matrix.rid }}.zip
          tag: ${{ github.ref }}

      - name: Upload binaries as artifact
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          path: dist/dofusdb-${{ matrix.rid }}.zip
          name: dofusdb-${{ matrix.rid }}.zip
          if-no-files-found: error