name: .NET - Build and Publish

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Install .NET 9.0 (for dotnet-releaser)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install .NET 10.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install dotnet-releaser
        shell: bash
        run: dotnet tool install --global dotnet-releaser

      - name: Build, Tests, Cover, Pack and Publish
        shell: bash
        run: dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml

permissions:
  contents: write