name: Continuous Deployment - Publish Libraries

on:
  release:
    types: [published]
  workflow_dispatch:
    dry-run:
      description: Whether to skip the publication of packages to the repositories
      type: boolean

jobs:
  build-publish:
    runs-on: ubuntu-latest
    
    permissions:
      actions: write
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET 10.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Compute version
        id: compute_version
        uses: ./.github/workflows/reusable-compute-version.yml
        with:
          build-name: main

      - name: Build
        run: dotnet build --configuration Release --property Version=${{ steps.compute_version.outputs.version }}

      - name: Test
        run: dotnet test --configuration Release --no-build
        
      - name: Pack
        run: dotnet pack --output nuget/ --property Version=${{ steps.compute_version.outputs.version }}
      
      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: libraries
          path: nuget/*.nupkg
          if-no-files-found: error
          
      - name: Publish nugets - Github
        if: ${{ !inputs.dry-run }}
        run: |
          foreach($File in (Get-ChildItem "nuget/" -Recurse -Include *.nupkg)) {
              dotnet nuget push $File --source github --api-key ${{ secrets.GITHUB_TOKEN }}
          }

      - name: Publish nugets - Nuget
        if: ${{ !inputs.dry-run }}
        run: |
          foreach($File in (Get-ChildItem "nuget/" -Recurse -Include *.nupkg)) {
              dotnet nuget push $File --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}