name: Continuous Integration - PR Build & Test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  compute_version:
    name: Compute version
    uses: ./.github/workflows/reusable-compute-version.yml
    with:
      build-name: pr
      
  build-and-test:
    runs-on: ubuntu-latest
    needs: compute-version
    
    permissions:
      checks: write
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET 10.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore --property Version=${{ needs.compute-version.outputs.version }}
        
      - name: Tests
        run: dotnet test --no-build --filter "FullyQualifiedName!~Tests.Live" --verbosity normal --logger trx
        
      - name: Live Tests 
        run: dotnet test --no-build --filter "FullyQualifiedName~Tests.Live" --verbosity normal --logger trx
        continue-on-error: true # Live tests might fail because of external factors like a service being down

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: (!cancelled())
        with:
          # Test results are written to each test project's directory under the TestResults directory
          trx_files: "**/TestResults/*.trx"

